#! /usr/bin/env python
import os.path
import sys
import os
import imp
from builder import PROJECTS_ROOT_PATH
from builder import printHelp
SConscript = None
firstRealArgI = 1
#in case we don't have any arguments
if len(sys.argv) <= firstRealArgI:
    #try to find the SConscript right here
    if os.path.exists(os.path.join(os.getcwd(),"SConscript")):
        firstRealArgI = firstRealArgI - 1
        SConscript = os.path.join(os.getcwd(),"SConscript")
    else:
        print "No SConscript files found"
        printHelp()
        exit()
else:
    #try to find the SConscript right here
    if os.path.exists(os.path.join(os.getcwd(),"SConscript")):
        firstRealArgI = firstRealArgI - 1
        SConscript = os.path.join(os.getcwd(),"SConscript")
    #try to find the SConscript in the specified absolute path
    elif os.path.exists(os.path.join(sys.argv[firstRealArgI],"SConscript")):
        SConscript = os.path.join(sys.argv[firstRealArgI],"SConscript")
    #try to find the SConscript in the specified relative to current path
    elif os.path.exists(os.path.join(os.getcwd(),sys.argv[firstRealArgI],"SConscript")):
        SConscript = os.path.join(os.getcwd(),sys.argv[firstRealArgI],"SConscript")
    #try to find the SConscript in the specified path from projects src root
    elif os.path.exists(os.path.join(PROJECTS_ROOT_PATH,'src',sys.argv[firstRealArgI],"SConscript")):
        SConscript = os.path.join(PROJECTS_ROOT_PATH,'src',sys.argv[firstRealArgI],"SConscript")
    else:
        print "No "+os.path.join(os.getcwd(),"SConscript")
        print "No "+os.path.join(sys.argv[firstRealArgI],"SConscript")
        print "No "+os.path.join(os.getcwd(),sys.argv[firstRealArgI],"SConscript")
        print "No "+os.path.join(PROJECTS_ROOT_PATH,'src',sys.argv[firstRealArgI],"SConscript")
        print "NO SConscript files found"
        printHelp()
        exit()
    
OTHER_ARGUMENTS = ""
ONLY_PROJECT_CLEANING_STAGE = 0
if len(sys.argv) > firstRealArgI + 1:
    for i in range(firstRealArgI+1, len(sys.argv)):
        if sys.argv[i] == '-h':
            printHelp()
            exit()
        if sys.argv[i] == '-r':
            os.system("python "+SConscript+" "+os.path.join(PROJECTS_ROOT_PATH,'src'))
            #imp.load_source('SConscript',os.path.dirname(SConscript))
            exit()
        if sys.argv[i] == '-c':
            print "ONLY CURRENT PROJECT WILL BE CLEAN"
            ONLY_PROJECT_CLEANING_STAGE = 1
            
        if sys.argv[i] == '-call':
            print "ALL DEPENDENCIES WILL BE CLEAN"
            OTHER_ARGUMENTS+=" -c"
        else:
            #FOR ALL EXCEPT -call
            OTHER_ARGUMENTS+=" "+sys.argv[i]
    #end for arguments
    
if ONLY_PROJECT_CLEANING_STAGE == 1:
    OTHER_ARGUMENTS+=" cleaning=1"
os.system("scons -f "+os.path.abspath(os.path.dirname(__file__))+"/Sconstruct SConscript="+SConscript+OTHER_ARGUMENTS)