import os.path
import sys
from helper import *

#--------------------------------------
#           Environment
#--------------------------------------
Import( 'env', 'args' )        # Import the common environment
#--------------------------------------
#            PROJECT
#--------------------------------------
args['PROGFileName'] = 'SnocsHelloWorld'
args['prj_env'] = env.Clone()          # Clone it so we don't make changes to the global one
args['prj_env'].Append(
    #LIBPATH = [],#snocs dependencies can be managed via AddDependency function
    #LIBS = [],#snocs dependencies can be managed via AddDependency function
    #LINKFLAGS = [],
    CPPPATH = [os.path.join(args['SCONSCRIPT_PATH'],'include')],
    #CPPDEFINES = [],
    #CCFLAGS = []
)
Default(PrefixTest(args, PrefixSources(args, 'src', [
    'main.c'
])))
#this is just a testing of cross project dependencies
AddOrdering(args,
    'SnocsTemplateTest_test',#ONLY AFTER TEST BUILDS
    #PATH TO THE PROJECT ABOVE:
    os.path.join(args['PROJECTS_SRC_PATH'],'github.com','osblinnikov','SNocs','examples','template')
)#this function orders the build, but not includes the lib fil
